### ISSUE TITLE
IE10: Object doesn't support property or method 'fill'

### ISSUE THREAD

**Issue by kawanet** [feross/buffer#121] opened 2016-06-18 16:07 UTC
It looks the current version 4.6.0 does not work on IE10.

- IE9 + buffer 4.6.0 - OK
- IE10 + buffer 4.6.0 - NG
- IE11 + buffer 4.6.0 - OK
- IE10 + buffer 4.1.0/4.5.1 - NG
- IE10 + buffer 3.6.0/4.0.0 - OK

**Comment by kawanet** [comment] 2016-06-18 16:10
How to reproduce the problem:

```sh
echo 'document.write([].join.call(Buffer(1).fill(123)));' > src.js 
browserify src.js -o out.js
echo '<script src="./out.js"></script>' > index.html 
```

- `123` on document body: OK
- `Object doesn't support property or method 'fill'` error on console: NG

**Comment by kawanet** [comment] 2016-06-18 16:28
This does not work on IE10:

```js
document.write([].join.call(Buffer(1).fill(123)));
```

This does work on IE10:

```js
document.write([].join.call(Buffer.prototype.fill.call(Buffer(1), 123)));
```

**Comment by kawanet** [comment] 2016-06-18 17:24
I got the reason.

The "IE10" I mentioned above is an IE10 mode on the IE11 switched with the built-in developer tools.

It works on the original IE10.

- IE10-on-IE11 has TYPED_ARRAY_SUPPORT = true
- The original IE10 has TYPED_ARRAY_SUPPORT = false

**Comment by nolanlawson** [comment] 2016-06-19 23:38
So if I understand correctly, this only fails when you're using IE11 but
trying to emulate older IEs via the doctype switch?

**Comment by kawanet** [comment] 2016-06-20 01:23
@nolanlawson Right.

I found this when testing another application for IE10 but on IE11.

![ie10](https://cloud.githubusercontent.com/assets/9765/16181030/9af35a06-36cf-11e6-9d8c-867e693067e8.png)

Any developers who want to test on the environment would face the problem.
It seems that it has happened since 12a3318 of v4.1.0.
The patch 23548e7 respects the new way of augmentation using `__proto__`.

**Comment by feross** [comment] 2016-06-22 11:11
Thanks for digging into this. I just confirmed what you found. This is definitely a developers-only edge case, but you're right to point out that the code that's checking for typed array augmentation should just check if `__proto__` can be set, since that's what we do now.

Released as 4.6.1.

**Closed by feross** 2016-06-22 11:11 UTC

**Comment by andreamancuso** [comment] 2017-03-24 09:12
Hello folks, I have come across this issue using native IE10 (on VirtualBox Win7). I suppose I'm just very unlucky?

**Comment by feross** [comment] 2017-03-24 17:55
@andreamancuso Please ensure that you're using the latest version of buffer. Try running `npm ls buffer` and confirm that the version is later than 4.6.1

**Comment by andreamancuso** [comment] 2017-03-24 18:12
Hi, my apologies, it was caused by the 'request' module in fact. I switched to isomorphic-fetch and everything is working fine now. 
Best, Andrea
