### ISSUE TITLE
New minor version break on PhantomJS

### ISSUE THREAD

**Issue by tiagolpadua** [feross/buffer#248] opened 2019-10-03 13:56 UTC
karma-typescript uses buffer as a dependency, the version 5.2.1 didnt require Uint8Array in the browser, so it runs on PhantomJS 2.1.1, but the new version 5.4.x breaks on PhantomJS 2.1.1 with:
PhantomJS 2.1.1 (Linux 0.0.0) ERROR: [36m'This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.'

This new minor version should not be backward compatible?

**Comment by vweevers** [comment] 2019-10-03 14:06
Duplicate of https://github.com/feross/buffer/issues/240

**Closed** 2019-10-06 18:16 UTC
