### ISSUE TITLE
typescript: Buffer bindings conflict with @types/node

### ISSUE THREAD

**Issue by jadbox** [feross/buffer#196] opened 2018-05-10 23:39 UTC
Sadly @types/react-dom uses @types/node that also declares a Buffer type. Is it possible to rename the type to like bufferWeb or something?

**Comment by feross** [comment] 2018-05-11 00:28
I don't use TypeScript. Please coordinate a solution with @ukstv who submitted the bindings. Happy to accept whatever PR the two of you send to address this issue.

**Comment by feross** [comment] 2018-05-11 00:29
Closing the issue since I don't plan to take any action here, but please feel free to continue discussion in this issue and to send a PR when you've decided how to handle it.

**Closed by feross** 2018-05-11 00:28 UTC

**Comment by ukstv** [comment] 2018-05-12 17:45
@jadbox Could you provide with an example package to reproduce the case, please?

**Comment by islommuhammad** [comment] 2018-07-30 11:00
same here

"buffer": "5.2.0",
"@types/node": "^8.5.9",
"typescript": "~2.7.1"

**Comment by ukstv** [comment] 2018-08-02 19:05
Gentlemen, vanilla Node and this package provide the same 'buffer' module. This is not a surprise the declarations for these are in conflict. I would suggest using 'safe-buffer' package or vanilla type declarations from node, that is to remove 'buffer' package from dependencies.

**Comment by feross** [comment] 2018-08-04 00:07
It's also worth noting that `require('buffer').Buffer` will always return the built-in Node.js buffer package, not the npm package called "buffer".

If you want to import the npm package "buffer", you need to use `require('buffer/').Buffer`.

**Comment by feross** [comment] 2018-08-04 06:50
Looks like there's a PR to fix the types here: https://github.com/feross/buffer/pull/214 Can someone familiar with Typescript review it / try it out?

**Comment by mi-mazouz** [comment] 2019-12-30 19:45
not working for me. version 5.4.3
