### ISSUE TITLE
Buffer.slice is broken for Windows Edge users and in Firefox developer edition

### ISSUE THREAD

**Issue by jcalfee** [feross/buffer#120] opened 2016-06-15 18:15 UTC
We noticed that some Windows Edge users and in the latest developer edition of Firefox (v49) Buffer slice is failing.   We successfully worked around the problem by setting  `TYPED_ARRAY_SUPPORT = false`.  The issue happens when this.subarray(start, end) returns the wrong results.  You can see the problem with this test: `new Buffer("abc").slice(0, 2) === "abc"` .. This will return true if you have the bug.  

I believe this.subarray is native so I have also reported this issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1280052
```js
Buffer.prototype.slice = function slice (start, end) {
...
 var newBuf
  if (Buffer.TYPED_ARRAY_SUPPORT) {
    newBuf = Buffer._augment(this.subarray(start, end))
  } else {
    var sliceLen = end - start
    newBuf = new Buffer(sliceLen, undefined)
    for (var i = 0; i < sliceLen; i++) {
      newBuf[i] = this[i + start]
    }
  }
...
```

**Comment by feross** [comment] 2016-06-15 18:40
It looks like you're using an old version of this library. You can use `npm ls buffer` to see which packages are depending on `buffer`. The current version of `buffer` is 4.6.0.

**Comment by feross** [comment] 2016-06-15 18:40
This issue is fixed in the latest version of buffer.

**Closed by feross** 2016-06-15 18:40 UTC

**Comment by nolanlawson** [comment] 2016-06-16 02:01
By any chance was an issue filed on Edge as well? We care a lot about library compat and want to make sure we don't break the ecosystem.

Here's [our issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/). A complete Gist to reproduce would be really helpful (or at least which version of `buffer` you're using so that we can reproduce).

**Comment by feross** [comment] 2016-06-16 02:55
@nolanlawson This issue was fixed by https://github.com/feross/buffer/pull/97 a while ago.

**Comment by nolanlawson** [comment] 2016-06-16 04:29
Ah OK, got it. I'll add a comment to the Mozilla bug.
